### ISSUE TITLE
Start an agent pool with 0 VM

### ISSUE THREAD

**Issue by ritazh** [wbuchwalter/Kubernetes-acs-engine-autoscaler#12]
I realize this depends on acs-engine...but something to think about.

**Comment by wbuchwalter** [comment]
It is something I was thinking about doing yes.  
I don't see any problem doing this with acs-engine, since we can get the VM size directly from the template.  
With ACS it is more problematic since we need at least one running agent to know which VM size is the agent pool configured to use.  
For now we can enable this only for acs-engine.
