### ISSUE TITLE
Handling num_nodes = 0 and --spare-agents 0?

### ISSUE THREAD

**Issue by noajshu** [wbuchwalter/Kubernetes-acs-engine-autoscaler#39]
I love this autoscaler and I am curious what it would take to fix the bugs when you have num_nodes=0 and / or spare_agents=0. I noticed some TODOs in the code, and was wondering if you're open to PRs on those.

**Comment by wbuchwalter** [comment]
**Note**: I have edited your issue, and split it in two for more clarity, see https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler/issues/40 for your other question

Thanks @noajshu !
I probably need to clean the TODOs. 
There was a time when I planned on supporting both ACS and acs-engine clusters. The comment about the issue with 0 agents is for ACS.

So if you set `--spare-agents 0`, your pool should be able to scale down to 0 agents (provided there is no system pods on this specific pool), and up again afterwards when you schedule some stuff. 
Let me know if you are having issues with this.

**Comment by noajshu** [comment]
Thank you for the info!

I am having difficulty with the --spare-agents feature and I'm not sure if it's a bug.
If I set --spare-agents 1, will the autoscaler launch nodes to ensure 1 spare agent? Or does that flag only <i>limit the termination</i> of idle nodes?

Here is my situation:
In my cluster I have 2 pools:
agentpool0 -- GPU pool
agentpool1 -- CPU only pool

I would like to scale the CPU and GPU nodes using different parameters (higher --spare-agents for CPU-only nodes), so I have run a CPU-only autoscaler like this:
```bash
python main.py --ignore-pools 'agentpool0' --resource-group '<myclusterresourcegroup>' --spare-agents '1' -vvv
```
There are currently 0 CPU nodes in pool 1. Although there are no pending pods, I expect the autoscaler to launch a new CPU node to maintain the --spare-agents 1. Instead it takes no action. Here is the log output:
```
2017-07-19 17:39:50,365 - autoscaler.cluster - INFO - ++++ Running Scaling Loop ++++++
2017-07-19 17:39:53,759 - autoscaler.cluster - INFO - Pods to schedule: 0
2017-07-19 17:39:53,760 - autoscaler.cluster - INFO - ++++ Scaling Up Begins ++++++
2017-07-19 17:39:53,760 - autoscaler.cluster - INFO - Nodes: 1
2017-07-19 17:39:53,760 - autoscaler.cluster - INFO - To schedule: 0
2017-07-19 17:39:53,760 - autoscaler.cluster - INFO - Pending pods: 0
2017-07-19 17:39:53,760 - autoscaler.cluster - INFO - ++++ Scaling Up Ends ++++++
2017-07-19 17:39:53,760 - autoscaler.cluster - INFO - ++++ Maintenance Begins ++++++
2017-07-19 17:39:53,760 - autoscaler.engine_scaler - INFO - ++++ Maintaining Nodes ++++++
2017-07-19 17:39:53,760 - autoscaler.engine_scaler - DEBUG - max_nodes_to_drain for pool agentpool1 : -1
2017-07-19 17:39:53,760 - autoscaler.cluster - INFO - ++++ Maintenance Ends ++++++
```
You can even see that max_nodes_to_drain (= `(pool.actual_capacity - self.spare_count)`) is -1, meaning it can at most terminate -1 nodes, but it doesn't actually launch +1 node.

**Comment by wbuchwalter** [comment]
`--spare-agents` instruct the autoscaler to never kill more than `(pool.actual_capacity - self.spare_count)` agents in the pool. So if you have `--spare-agents 1` and you currently have 4 agents in your pool, the AS will kill 3 agents at most.  
But the autoscaler will not launch new nodes to meet the `--spare-agents` count. If there is 0 agent in the pool that means the user killed the VM manunally (since the autoscaler couldn't have done it itself if you have `--spare-agents 1`), and so the autoscaler will not bypass the user choice on this by recreating the node.

If you schedule enough CPU loads on your cluster, first your existing GPU VMs will be filled, but then you will have some pending pods that won't fit on the GPU nodes. At this point the AS will trigger a scale up and recreate some CPU nodes.   
At this point if you kill all your pods, the AS will kill all existing CPU nodes but one.

https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler/issues/40 would be an easier way to recover from this.

**Comment by wbuchwalter** [comment]
Closing as I assumed this answered your question.

**Comment by noajshu** [comment]
Yes, thanks!
