### ISSUE TITLE
Need Help on Autoscaling of the Agent on Kubernetes (Azure ACS)

### ISSUE THREAD

**Issue by hamid2013** [wbuchwalter/Kubernetes-acs-engine-autoscaler#55]
I have created the ACS kubernetes using the terraform, and then use this repo for the autoscaler. After that i created the load on the agent but due to some reason the agent is not getting scale out.
How to check or troubleshoot for this.

**Comment by wbuchwalter** [comment]
`kubernetes-acs-engine-autoscaler` is a node-level autoscaler. It will scale the nodes, not the pods.
If you want to scale based on some load, you should set up an [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) that will scale the pods based on some metrics (such as CPU usage).
If HPA scales more pods than can fit on your cluster `kubernetes-acs-engine-autoscaler` will detect it and scale the nodes so that everything can run.

If you already have configured HPA, then you should be able to see what's wrong by just doing `kubectl logs` on the autoscaler container.

**Comment by hamid2013** [comment]
Ok got your point, now if i am adding additional deployments(with pods) does the autoscaler work on that case.

1. Also on the logs it showing like below all the time. What exactly means by "state: under-utilized-undrainable"

2017-09-26 20:28:43,863 - autoscaler.cluster - INFO - ++++ Running Scaling Loop ++++++
2017-09-26 20:28:43,914 - autoscaler.cluster - INFO - Pods to schedule: 0
2017-09-26 20:28:43,914 - autoscaler.cluster - INFO - ++++ Scaling Up Begins ++++++
2017-09-26 20:28:43,914 - autoscaler.cluster - INFO - Nodes: 1
2017-09-26 20:28:43,914 - autoscaler.cluster - INFO - To schedule: 0
2017-09-26 20:28:43,915 - autoscaler.cluster - INFO - Pending pods: 0
2017-09-26 20:28:43,915 - autoscaler.cluster - INFO - ++++ Scaling Up Ends ++++++
2017-09-26 20:28:43,915 - autoscaler.cluster - INFO - ++++ Maintenance Begins ++++++
2017-09-26 20:28:43,915 - autoscaler.engine_scaler - INFO - ++++ Maintaining Nodes ++++++
2017-09-26 20:28:43,918 - autoscaler.engine_scaler - INFO - node: k8s-agentpool1-19135991-0                                                   state: under-utilized-undrainable
2017-09-26 20:28:43,919 - autoscaler.cluster - INFO - ++++ Maintenance Ends ++++++

2. Manually i have increased the number of worker nodes by modifying the parameter.json file and ran the az command to increase that. But after some time the node are getting deleted so is it because of autoscaler running on that cluster and no workload is running on those worker machines.

**Comment by wbuchwalter** [comment]
1. `under-utilized-undrainable` means that the node is barely used (under 30% of it's capacity by default), but because the pods running there are not replicated anywhere else (such as system pods, or user pods that are not replicated) the autoscaler won't shut down this node to avoid service disruption.

2. Yes most likely. It seems you have barely anything running in your cluster, so even if you add more nodes, the autoscaler will see that they are not used and start deleting them.
If you don't want this nodes to be deleted you can use the `--spare-agents` flag and specify how many nodes per pool you want to keep at all time.

If you want to trigger a scale out, you can schedule a bunch of pods with a specific CPU requests. If you schedule enought of them, at some point your cluster won't be able to accomodate all of them and the autoscaler will start creating new nodes.

**Comment by hamid2013** [comment]
Thanks wbuchwalter for all the info..

One more question, to make the autoscaler works whatever deployments we are running on the Kubernetes cluster, all should have the CPU reservation and limit.

**Comment by wbuchwalter** [comment]
Not sure I understand your last question.
For every container you schedule on the cluster, you should specify either a CPU request or limit (or both). This way the autoscaler is able to know what can fit where and how many new VMs to create when scaling.
